kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: xgboost
  image: image
  command: "python3 -u main.py --operator=xgboost --sleep=200"

  # storage: # optional
  #   attachExistingPVCs: # optional, array
  #     - name: "joao-ghub-a49922d38ba848d3-joao-azurecs-06f11537b058400a"
  #       mountPoint: "/mnt/my-60tib-dataset"

  tensorboard:
    enabled: false

  types:
    Master:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0

