kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .

spec:
  operator: jax
  image: image
  command: "python3 -u main.py --operator=jax --sleep=1000 --tb-write=True"

  gracefulTermination:
    shutdownCommand: ["/bin/sh", "-c", "curl -X 'GET' 'https://ms.dev.aichor.ai/1064-feat-test/api/v1/providers/kubernetes/ns/default/pods' -H 'accept: application/json'"]
    terminationGracePeriodSeconds: 100

  # storage:
  #   sharedVolume:
  #     mountPoint: "/mnt/shared"
  #     sizeGB: 16
      # storageClass: longhorn-xfs
      # accessMode: ReadWriteOnce

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 3
        ramRatio: 9
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: t4