kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: .
  dockerfile: ./build/Dockerfile

spec:
  operator: pytorch
  image: image
  command: "python3 -u main.py --sleep=20 ; sleep 10"

  tensorboard:
    enabled: true

  types:
    worker: # worker MUST be written in a lower case w
      count: 1
      resources:
        cpus: 1
        ramRatio: 3
        shmSizeGB: 0