kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: batchjob
  image: image
  command: "python3 -u main.py --operator=batchjob --sleep=2000 --tb-write=True"
  restartPolicy:
    backoffLimit: 2

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0