
kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  context: smoke-test # smoke-test folder
  dockerfile: ./build/Dockerfile

spec:
  operator: tf
  image: image
  command: "python3 -u main.py --operator=tf --sleep=20 --tb-write=True"
  
  storage: # optional
    attachExistingPVCs: # optional, array
      - name: "joao-reg-ef03d4784a5b4e2a-joao1-bf4d19860b8c42db"
        mountPoint: "/mnt/my-60tib-dataset"

  tensorboard:
    enabled: true
  
  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
        # accelerators: # optional
        #   gpu:
        #     count: 1
        #     type: gpu
        #     product: t4
            
        # extraSelectors: # optional
        #   karpenter.sh/capacity-type: spot







        # extraSelectors: # optional 
        #   karpenter.sh/capacity-type: spot
