kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/Dockerfile
  context: .

spec:
  operator: tf
  image: image
  command: "python3 -u main.py --operator=tf --sleep=300 --tb-write=True"

  storage:
    storage:
    attachExistingPVCs: # optional, array
      - name: "joao-gp2-45225e91fd8346df-joao-gp2-bc0a727ae0a3457f"
        mountPoint: "/mnt/my-60tib-dataset"

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4

